In [4]:
import pandas as pd
pd.set_option('display.max.row', 20)

In [5]:
df = pd.read_csv(r"C:\Users\kallzz\Desktop\Data Analytics Stuff\Data Analyst - Boot Camp\Python - Jupyter Notebooks\Datasets\world_population.csv")

In [6]:
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [7]:
# set index - method 1
df = pd.read_csv(r"C:\Users\kallzz\Desktop\Data Analytics Stuff\Data Analyst - Boot Camp\Python - Jupyter Notebooks\Datasets\world_population.csv", index_col = 'Country')
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [12]:
# reset index
df.reset_index(inplace = True)
df

,index,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [14]:
df.set_index('Country')

,index,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,,
Afghanistan,0,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,1,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,2,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,3,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,4,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,229,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,230,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,231,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,232,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,233,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [17]:
# multi index
df.set_index(['Continent','Country'], inplace=True)

In [18]:
df.sort_index()

                            index  Rank CCA3      Capital  2022 Population  \
Continent     Country
Africa        Algeria           2    34  DZA      Algiers       44903225.0
              Angola            5    42  AGO       Luanda       35588987.0
              Benin            21    77  BEN   Porto-Novo       13352864.0
              Botswana         26   144  BWA     Gaborone        2630296.0
              Burkina Faso     31    58  BFA  Ouagadougou       22673762.0
...                           ...   ...  ...          ...              ...
South America Paraguay        161   109  PRY     Asunción        6780744.0
              Peru            162    44  PER         Lima       34049588.0
              Suriname        199   170  SUR   Paramaribo         618040.0
              Uruguay         223   133  URY   Montevideo        3422794.0
              Venezuela       227    51  VEN      Caracas       28301696.0

                            2020 Population  2015 Population  2010 Population  \
Continent     Country
Africa        Algeria            43451666.0       39543154.0       35856344.0
              Angola             33428485.0       28127721.0       23364185.0
              Benin              12643123.0       10932783.0        9445710.0
              Botswana            2546402.0        2305171.0        2091664.0
              Burkina Faso       21522626.0       18718019.0       16116845.0
...                                     ...              ...              ...
South America Paraguay            6618695.0        6177950.0        5768613.0
              Peru               33304756.0       30711863.0       29229572.0
              Suriname             607065.0         575475.0         546080.0
              Uruguay             3429086.0        3402818.0        3352651.0
              Venezuela          28490453.0       30529716.0       28715022.0

                            2000 Population  1990 Population  1980 Population  \
Continent     Country
Africa        Algeria            30774621.0       25518074.0       18739378.0
              Angola             16394062.0       11828638.0        8330047.0
              Benin               6998023.0        5133419.0        3833939.0
              Botswana            1726985.0        1341474.0         938578.0
              Burkina Faso       11882888.0        9131361.0        6932967.0
...                                     ...              ...              ...
South America Paraguay            5123819.0        4059195.0        3078912.0
              Peru               26654439.0       22109099.0       17492406.0
              Suriname             478998.0         412756.0         375112.0
              Uruguay             3292224.0        3117012.0        2953750.0
              Venezuela                 NaN       19750579.0       15210443.0

                            1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
Africa        Algeria            13795915.0   2381741.0            18.8531
              Angola              6029700.0   1246700.0            28.5466
              Benin               3023443.0    112622.0           118.5635
              Botswana             592244.0    582000.0             4.5194
              Burkina Faso        5611666.0    272967.0            83.0641
...                                     ...         ...                ...
South America Paraguay            2408787.0    406752.0            16.6705
              Peru               13562371.0   1285216.0            26.4933
              Suriname             379918.0    163820.0             3.7727
              Uruguay             2790265.0    181034.0            18.9069
              Venezuela          11355475.0         NaN            30.8820

                            Growth Rate  World Population Percentage
Continent     Country
Africa        Algeria            1.0164                         0.56
              Angola             1.0315                         0.45
              Benin              1.0274                         0.17
              Botswana           1.0162                         0.03
              Burkina Faso       1.0259                         0.28
...                                 ...                          ...
South America Paraguay           1.0115                         0.09
              Peru               1.0099                         0.43
              Suriname           1.0082                         0.01
              Uruguay            0.9990                         0.04
              Venezuela          1.0036                         0.35

[234 rows x 16 columns]

In [19]:
df.sort_index(ascending = [True, False]) # sorts Capital in asc and country in dsc

                              index  Rank CCA3       Capital  2022 Population  \
Continent     Country
Africa        Zimbabwe          233    74  ZWE        Harare       16320537.0
              Zambia            232    63  ZMB        Lusaka       20017675.0
              Western Sahara    230   172  ESH      El Aaiún         575986.0
              Uganda            217    31  UGA       Kampala       47249585.0
              Tunisia           212    79  TUN         Tunis       12356117.0
...                             ...   ...  ...           ...              ...
South America Colombia           42    28  COL        Bogota       51874024.0
              Chile              40    65  CHL      Santiago       19603733.0
              Brazil             27     7  BRA      Brasilia      215313498.0
              Bolivia            24    80  BOL         Sucre       12224110.0
              Argentina           8    33  ARG  Buenos Aires       45510318.0

                              2020 Population  2015 Population  \
Continent     Country
Africa        Zimbabwe             15669666.0       14154937.0
              Zambia               18927715.0              NaN
              Western Sahara         556048.0         491824.0
              Uganda               44404611.0       37477356.0
              Tunisia              12161723.0       11557779.0
...                                       ...              ...
South America Colombia             50930662.0       47119728.0
              Chile                19300315.0       17870124.0
              Brazil              213196304.0      205188205.0
              Bolivia              11936162.0       11090085.0
              Argentina            45036032.0       43257065.0

                              2010 Population  2000 Population  \
Continent     Country
Africa        Zimbabwe             12839771.0       11834676.0
              Zambia               13792086.0        9891136.0
              Western Sahara         413296.0         270375.0
              Uganda               32341728.0       24020697.0
              Tunisia              10895063.0        9893316.0
...                                       ...              ...
South America Colombia                    NaN       39215135.0
              Chile                17004162.0       15351799.0
              Brazil              196353492.0      175873720.0
              Bolivia              10223270.0        8592656.0
              Argentina            41100123.0       37070774.0

                              1990 Population  1980 Population  \
Continent     Country
Africa        Zimbabwe             10113893.0        7049926.0
              Zambia                7686401.0        5720438.0
              Western Sahara         178529.0         116775.0
              Uganda               17586630.0       13284026.0
              Tunisia               8440023.0        6578156.0
...                                       ...              ...
South America Colombia             32601393.0       26176195.0
              Chile                13342868.0       11469828.0
              Brazil              150706446.0      122288383.0
              Bolivia               7096194.0        5736088.0
              Argentina            32637657.0       28024803.0

                              1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
Africa        Zimbabwe              5202918.0    390757.0            41.7665
              Zambia                4281671.0    752612.0            26.5976
              Western Sahara          76371.0    266000.0             2.1654
              Uganda               10317212.0    241550.0           195.6100
              Tunisia               5047404.0    163610.0            75.5218
...                                       ...         ...                ...
South America Colombia             20905254.0   1141748.0            45.4339
              Chile                 9820481.0    756102.0            25.9274
              Brazil               96369875.0   8515767.0            25.2841
              Bolivia               4585693.0   1098581.0            11.1272
              Argentina            23842803.0   2780400.0            16.3683

                              Growth Rate  World Population Percentage
Continent     Country
Africa        Zimbabwe             1.0204                         0.20
              Zambia               1.0280                         0.25
              Western Sahara       1.0184                         0.01
              Uganda               1.0304                         0.59
              Tunisia              1.0076                         0.15
...                                   ...                          ...
South America Colombia             1.0069                         0.65
              Chile                1.0057                         0.25
              Brazil               1.0046                         2.70
              Bolivia              1.0120                         0.15
              Argentina            1.0052                         0.57

[234 rows x 16 columns]

In [20]:
df.loc['Africa']

,index,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Algeria,2,34,DZA,Algiers,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
Angola,5,42,AGO,Luanda,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
Benin,21,77,BEN,Porto-Novo,13352864.0,12643123.0,10932783.0,9445710.0,6998023.0,5133419.0,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
Botswana,26,144,BWA,Gaborone,2630296.0,2546402.0,2305171.0,2091664.0,1726985.0,1341474.0,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
Burkina Faso,31,58,BFA,Ouagadougou,22673762.0,21522626.0,18718019.0,16116845.0,11882888.0,9131361.0,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tunisia,212,79,TUN,Tunis,12356117.0,12161723.0,11557779.0,10895063.0,9893316.0,8440023.0,6578156.0,5047404.0,163610.0,75.5218,1.0076,0.15
Uganda,217,31,UGA,Kampala,47249585.0,44404611.0,37477356.0,32341728.0,24020697.0,17586630.0,13284026.0,10317212.0,241550.0,195.6100,1.0304,0.59
Western Sahara,230,172,ESH,El Aaiún,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Zambia,232,63,ZMB,Lusaka,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,233,74,ZWE,Harare,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [21]:
df.loc['Africa', 'Algeria']

index                                   2
Rank                                   34
CCA3                                  DZA
Capital                           Algiers
2022 Population                44903225.0
2020 Population                43451666.0
2015 Population                39543154.0
2010 Population                35856344.0
2000 Population                30774621.0
1990 Population                25518074.0
1980 Population                18739378.0
1970 Population                13795915.0
Area (km²)                      2381741.0
Density (per km²)                 18.8531
Growth Rate                        1.0164
World Population Percentage          0.56
Name: (Africa, Algeria), dtype: object

In [22]:
df.iloc[1]

index                                  1
Rank                                 138
CCA3                                 ALB
Capital                           Tirana
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: (Europe, Albania), dtype: object

In [23]:
df.iloc[1,1] # it doesn't work with multi indexes

138